### ISSUE TITLE
some excel files are missing

### ISSUE THREAD

**Issue by ZihanGit** [jiali1025/Automatic_Strain_Sensor_Design#6]
Hi, 
I am very interest about your work. I found some data file refers in the script is not provided (i.e. the files in ./excel/ folder). May I have these files and have a try of your codes.

Thank you very much.

**Comment by jiali1025** [comment]
Dear Zihan,

The excel files are the table S2 in the supplementary material. All the data is in the supplementary material of the paper. Since there are several rounds so they are more clearly described in the SI.

**Comment by zzfanfan** [comment]
Hi,
I am interested in your work. I have also encountered a similar data problem while running the script. Specifically, I couldn't find the ./excel/Data_loader_Round12.xlsx file in the supplementary material. I would appreciate it if you could provide some clarification. Thank you very much.

**Comment by jiali1025** [comment]
> Hi, I am interested in your work. I have also encountered a similar data problem while running the script. Specifically, I couldn't find the ./excel/Data_loader_Round12.xlsx file in the supplementary material. I would appreciate it if you could provide some clarification. Thank you very much.

Hi, thanks for your interest. The data is in table S2, not created in another separate excel file. You can copy the data to an excel data format if needed.

**Comment by zzfanfan** [comment]
Thank you very much for your reply. In run_active_learning.py, I have copied the data to Excel, but it still cannot run completely due to the problem with the file content format. If possible, I wonder if I can get a more complete file or a more detailed running process. Thank you very much.
